# Generated by Django 4.1.7 on 2023-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university_id',
            field=models.CharField(default='2011657042', max_length=10),
        ),
    ]
