# Generated by Django 4.1.7 on 2023-10-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='days_return',
            field=models.CharField(blank=True, default='100', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(blank=True, default='100', max_length=100, null=True),
        ),
    ]
