# Generated by Django 4.1.7 on 2023-11-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_is_verified_profile_verified_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
