# Generated by Django 4.1.7 on 2023-11-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
