# Generated by Django 4.1.7 on 2023-11-03 10:04

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to=app1.models.user_directory_path),
        ),
    ]
