# Generated by Django 4.1.7 on 2023-11-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='brand-1.png', null=True, upload_to='image'),
        ),
    ]
