# Generated by Django 4.1.7 on 2023-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
