# Generated by Django 4.1.7 on 2023-11-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistaredProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='university_id',
            field=models.CharField(default='2011657042', max_length=10),
        ),
    ]
