# Generated by Django 4.1.7 on 2023-11-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_delete_registaredprofile_profile_university_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
