# Generated by Django 4.1.7 on 2023-11-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_profile_university_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistaredProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(default='2011657042', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university_id',
        ),
    ]
